### ISSUE TITLE
Feature: Single-level interpolation

### ISSUE THREAD

**Issue by guybedford** [guybedford/chomp#100]
It could be valuable to support distinguishing between deep globbing interpolation and single level interpolation (`**` v `*`) via eg `##` and `#`.

The suggestion would be to rename the current form to `##` so that:

```toml
[[task]]
target = 'lib/##.js'
dep = 'src/##.ts'
```

would mean that deep folders can be globbed and output by the interpolation.

Then single level interpolation would be `#`:

```toml
[[task]]
target = 'lib/#.js'
dep = 'src/#.ts'
```

Using a `#` in target or dep and a `##` in the other would throw an error informing to use one or the other form.

I hope this wouldn't be too confusing, and it's an unfortunate early breaking change, but it seems like the right direction for interpolation for me, while retaining its linear and reversible properties.
