### ISSUE TITLE
Extend environment replacements to other strings

### ISSUE THREAD

**Issue by guybedford** [guybedford/chomp#123]
One example is deps themselves for interpolations:

```toml
[[task]]
target = './build/##'
deps = ['./cmd/##', '${{DEP}}/*.go', './src/**/*.go']
run = '''
  go build -o $TARGET $DEP
'''
```
