### ISSUE TITLE
Support watching files not yet created

### ISSUE THREAD

**Issue by zachsa** [guybedford/chomp#126]
I get this error

>thread 'main' panicked at 'Watching files not yet created is not yet supported, in depending on .ssr/index.js. This should be supported, please post an issue on GitHub!', src/task.rs:1335:29

In this case the `.ssr/index.js` file is created via a Rollup build, the task looks like this:

```toml
[[task]]
name = 'rollup:ssr'
deps = ['ssr/**/*.jsx']
run = 'rollup -c rollup/server.config.js'
```

Since rollup follows imports I run rollup once whenever a jsx file changes. But then in subsequent tasks I have to depend on the name of the task, not the output of the task (.ssr/index.js)
