### ISSUE TITLE
env variables are spilled between tasks

### ISSUE THREAD

**Issue by zachsa** [guybedford/chomp#127]
With an `index.js` file:

```js
console.log(process.env.NODE_ENV)
```

This workflow

```toml
[[task]]
name = 'two'
deps = ['one']
run = "node index.js"

[[task]]
name = 'one'
template = 'jspm'
env = ['node', 'production', 'module']
```

The log is 'production'.

If I change task one: env = ['node', 'development', 'module'], then the log is 'development'.

Is this intentional? I was expecting that the 'two' task would have the default env rather than env variables specified for previous tasks. The specific case is that I want to generate 'production' import maps (I think this will get me production builds of all the libraries), but set my NODE_ENV variable to development for the server start

**Comment by guybedford** [comment]
I replicated this example with:

```toml
version = 0.1
extensions = ['chomp@0.1:jspm']

[[task]]
name = 'two'
deps = ['one']
run = 'node index.js'

[[task]]
name = 'one'
template = 'jspm'
dep = 'in.html'
target = 'out.html'
[task.template-options]
env = ['node', 'production', 'module']
```

But I get `undefined` in the log since there is nothing in any of the above that actually sets `process.env.NODE_ENV`.

I think you may be confusing `env` in JSPM generator and `ENV` in Chomp which are completely separate things.

In JSPM generator the development production conditions alter which modules are loaded. If `index.js` is relying on an import map itself then some dependency is likely writing `process.env.NODE_ENV`.
