### ISSUE TITLE
Define common dependency tasks

### ISSUE THREAD

**Issue by guybedford** [guybedford/chomp#132]
When a task has a long intricate list of dependencies, it can be useful to support a wrapper task which acts as a single node to capture those dependencies:

```toml
[[task]]
name = 'commondeps'
deps = ['src/app.js', 'src/other.js', 'src/files/*.js']
```

where various tasks can then depend on `commondeps` once to get that same list. Currently this pattern doesn't work but it should be able to properly carry the invalidation information through.
