### ISSUE TITLE
Interpolation self-exclusion

### ISSUE THREAD

**Issue by guybedford** [guybedford/chomp#133]
It's useful to use interpolation to define minification:

```toml
[[task]]
dep = 'dist/#.js'
target = 'dist/#.min.js'
```

The problem with the above is that it has recursive behaviour.

To avoid this, we could automatically cause the target pattern to negate the dependency pattern in interpolation.

That is, if the target match matches the dependency glob, we automatically exclude this match set by default.

Seems like it could well be a sensible rule to add.
