### ISSUE TITLE
An alternative to "run" that allows specifying a path.

### ISSUE THREAD

**Issue by Bubblyworld** [guybedford/chomp#163]
It would be nice if there was a way to specify a path to a file to run, rather than inlining the script. Something like this:

```toml
[[task]]
name = "generate:api-docs"
engine = "node"
run = "./path/to/my/script.js"
```

Inlining the scripts makes development of extensions a pain.
