### ISSUE TITLE
Custom check functions

### ISSUE THREAD

**Issue by guybedford** [guybedford/chomp#23]
Currently the `target_check` field can be used to switch between `"mtime"` and `"exists"` checks for targets.

It might be useful to permit some kind of check scripting, for example, something like:

```toml
[[task]]
  deps = ['file.txt']
  target_check = "script"
  check_script = """([...deps], target) => {
    return deps.every(dep.mtime > X && dep.source.matches(/some text/));
  }"""
```

This would be sufficient to implement eg package.json version checks for npm installs.
