### ISSUE TITLE
Discussion: visibility of template dependencies and args

### ISSUE THREAD

**Issue by canadaduane** [guybedford/chomp#32]
From https://github.com/guybedford/chomp/pull/31#issuecomment-1010201851:

> Templates are functions that output a list of tasks, where those tasks in
turn can use templates. The jspm template will output the call to the
necessary npm template for JSPM to work, with the global option making auto
install configurable.

I think what's a bit tricky from a dev standpoint is that there is some "magic" happening inside that is difficult to reason about. What templates depend on what other templates? What args or options are available if I use this template vs. that template?

I'm trying to think of a way to make this easier to see inside. Possibly a `chomp` command line option that reads the chompfile and lists templates, its dependencies, and the options for all of these? I don't love it, but it's better than trying to find the template sources and learning about internals, I suppose.

> Would calling it global-options.npm seem clearer? It can be useful to eg
configure a global Babel config this way for all Babel templates to avoid
repetition so that’s why I was making sure that connection was clear first
and foremost.

I like the goal here, I'm just not sure about how to make invisible things more visible.

**Comment by guybedford** [comment]
There's a few perspectives here since it's a usability question more than an architecture question, so I would value your feedback on some of the below approaches. Naming is also an important perspective here.

Firstly, I agree it might not be the best way to introduce the global template options. We could still enable `auto-install` as being set per template with the tempaltes then passing it to the npm template.

Here's one possible naming change turning it into just "options", then introducing auto-install per task first:

```toml
[[task]]
  template = "svelte"
  [task.options]
    auto-install = true
```

Then later on we could introduce the package manager customization as a global option:

```toml
[default-options.npm]
  package-manager = 'pnpm'
```

Finally, we could then later on when a file has lots of `auto-install` properties, mention that this can also be set as a global npm option:

```toml
[default-options.npm]
  package-manager = 'pnpm'
  auto-install = 'npm'
```

Would the above offer clarify on this at all? I'm not so worried about users understanding the template model. Like you don't need to know all the details of the Rust macro model to use Rust macros most users don't need to know anything about what is happening underneath here.

In terms of the concern about there being invisible stuff going on, large I think the Rust macro arguments do apply - as long as the user knows the effect, it doesn't matter.

Another possibility might be to offer an `--eject-templates` argument to the CLI that would convert the template invocations into simple tasks removing all the template usages.

For example:

```toml
[[task]]
  template = 'npm'
  [task.options]
    package-manager = 'pnpm'
    packages = ["react", "react-dom"]
    auto-install = true
```

would, when calling `chomp --eject-templates`, rewrite the `chompfile.toml` to:

```toml
[[task]]
  deps = ["npm:init"]
  run = "pnpm install react react-dom"

[[task]]
  name = "npm:init"
  target = "package.json"
  run = "pnpm init -y"
```

Another option as you describe could be to have some visualization calls to see the above output as text, say via `chomp --show-tasks`. Perhaps that might be more flexible in that `chomp --show-tasks > chompfile.toml` could be the same as an eject.
