### ISSUE TITLE
Engines

### ISSUE THREAD

**Issue by guybedford** [guybedford/chomp#4]
It would be useful to have an engines field that can permit different runtime engines, with the default effectively being Bash / Powershell.

For example a Node.js engine would allow directly writing Node.js code in tasks:

```toml
[[task]]
  target = "copy-file.js"
  deps = ["file.js"]
  engine = "nodejs"
  run = """
    import { writeFileSync } from 'fs';
    writeFileSync('./file.js', readFileSync(process.env.DEP));
  """
```
