### ISSUE TITLE
Chomp task that runs chomp on a subfolder errors not propagating

### ISSUE THREAD

**Issue by guybedford** [guybedford/chomp#98]
For example:

```toml
[[task]]
run = 'chomp -c sub/chompfile.toml task
```

where the subtask is a task that fails. (the issue was seen on Linux).
